truncate table on_air_12h;
truncate table on_air24h;
truncate table on_air_36h;
TRUNCATE `scaled_on_air`;
TRUNCATE table audit_on_air;
TRUNCATE `reporte_comentario`;
delete from ticket_on_air;
delete from preparation_stage;
delete from precheck;
delete from follow_up_12h;
delete from follow_up_24h;
delete from follow_up_36h;
